### PR TITLE
Enhancing Mobile Responsiveness

### PR DESCRIPTION
**Pull request by margaretmwaura**

### CODE REVIEW

**Comment by CollActionOfficial** [comment]
1. pasting the same piece of code on 5 different places is code duplication, which should be prevented where possible. @Xazin Do you perhaps have a suggestion on how Margaret could fix this?
2. Decreasing screen width now yields the image below instead of the burger in the top right corner

image

**Comment by dastrong** [comment]
Regarding the duplication mentioned above, just refactor to something like this:
```jsx
// extract the close behavior into a separate function
const closeNavbar = () => setNavbar(false);

// remove the legacyBehavior prop & add the event handlers to the Next link
<NextLink
  href="..."
  className="..."
  onClick={closeNavbar}
  onKeyPress={closeNavbar}
>
  {t('app:navbar.projects')}
</NextLink>
```

Other tasks:
- add a transparent border on the open/close button to stop the layout shift it gets when focused
- the (a & button) elements in the mobile menu need to be styled for mobile as well

**Comment by CollActionOfficial** [comment]
@margaretmwaura How's it going?

**Comment by margaretmwaura** [comment]
> @margaretmwaura How's it going?

Will give an update to this by EOD

**Comment by margaretmwaura** [comment]
> Regarding the duplication mentioned above, just refactor to something like this:
> 
> ```js
> // extract the close behavior into a separate function
> const closeNavbar = () => setNavbar(false);
> 
> // remove the legacyBehavior prop & add the event handlers to the Next link
> <NextLink
>   href="..."
>   className="..."
>   onClick={closeNavbar}
>   onKeyPress={closeNavbar}
> >
>   {t('app:navbar.projects')}
> </NextLink>
> ```
> 
> Other tasks:
> 
> * add a transparent border on the open/close button to stop the layout shift it gets when focused
> * the (a & button) elements in the mobile menu need to be styled for mobile as well

Hi @dastrong , this has helped, thank you, you can review again

**Comment by margaretmwaura** [comment]
> 1. pasting the same piece of code on 5 different places is code duplication, which should be prevented where possible. @Xazin Do you perhaps have a suggestion on how Margaret could fix this?
> 2. Decreasing screen width now yields the image below instead of the burger in the top right corner
> 
> image

This has been resolved, kindly review again

**Comment by tomsiebring** [comment]
Looks good to me! what do you think @dastrong ?

**Comment by CollActionOfficial** [comment]
@dastrong

**Comment by dastrong** [comment]
> @dastrong

Yup, LGTM.

**Review by dastrong — APPROVED** [review]

**Pull request merged**
