### PR TITLE
refactor: Refactor donate page and related files

### PR DESCRIPTION
**Pull request by mudiagauwojeya**
#Refactor Donate
Below is a screenshot of most of the changes contained in this PR. 

Screenshot from 2022-12-13 16-06-43

### CODE REVIEW

**Comment by mudiagauwojeya** [comment]
Please, do not merge this just yet. Let me fix the media query first and push the changes. @tomsiebring

**Comment by mudiagauwojeya** [comment]
@tomsiebring This PR is ready for review now, please.

**Comment by CollActionOfficial** [comment]
image

1) Text and subtext in hero should align with [CONTENT DOC](https://docs.google.com/spreadsheets/d/1qW7rmrZY7hnLK7wHK55wqjNAQqOHRYchqpxLkI4FPGs/edit?usp=sharing) (in this case: "Head: Donate to support our mission" instead of "Become a supporter", and no subtext)
2) localisation does not seem to work. When I click on the NL flag, the English text is still shown. The content DOC has Dutch translations for each section of the page.

**Comment by mudiagauwojeya** [comment]
@CollActionOfficial some translations are missing. I have included a screenshot of them here.
Screenshot from 2022-12-19 12-16-23
Screenshot from 2022-12-19 12-16-36
Screenshot from 2022-12-19 12-17-10

- the translation for the buttons' text
- the translation for the form headlines (Recurring donation/One-time donation)
- the translation for "Don't have a credit card?..."
- the translation for the privacy policy statement under the continue button
- the translation for "Frequently Asked Questions"

**Comment by tomsiebring** [comment]
**- the translation for the buttons’ text**
Continue == Verder
Recurring donation == Herhalende donatie
One-time donation == Eenmalige donatie

**- the translation for the form headlines (Recurring donation/One-time donation)**
Recurring donation == Herhalende donatie
Ik wil CollAction steunen met een maandelijks donatie

One-time donation == Eenmalige donatie
Ik wil CollAction steunen met een eenmalige donatie (instead of “something”)

**- the translation for "Don't have a credit card?…”**
Heeft u geen credit card? Geen probleem. Selecteer SEPA Direct Debit in de volgende stap. (Instead of "Don’t have … next step.”)

**- the translation for the privacy policy statement under the continue button**
Door te doneren gaat u akkoord met onze (privacyvoorwaarden)[/privacy] (Instead of “By donating … (Privacy policy)[/privacy]")

**- the translation for "Frequently Asked Questions”**
Veelgestelde Vragen

**Comment by CollActionOfficial** [comment]
Hi Mudiaga,

Thanks for replying on GitHub! Apologies for the incompleteness. Please find below the translations :) I’ll also put these in the CONTENT DOC and on GitHub in the thread. Keep up the good work!

Tom

> the translation for the buttons’ text
Continue == Verder
Recurring donation == Herhalende donatie
One-time donation == Eenmalige donatie
> the translation for the form headlines (Recurring donation/One-time donation)
Recurring donation == Herhalende donatie
Ik wil CollAction steunen met een maandelijks donatie

One-time donation == Eenmalige donatie
Ik wil CollAction steunen met een eenmalige donatie (instead of “something”)
> the translation for "Don't have a credit card?…”
Heeft u geen credit card? Geen probleem. Selecteer SEPA Direct Debit in de volgende stap. (Instead of "Don’t have … next step.”)
> the translation for the privacy policy statement under the continue button
Door te doneren gaat u akkoord met onze (privacyvoorwaarden)[/privacy] (Instead of “By donating … (Privacy policy)[/privacy]")
> the translation for "Frequently Asked Questions”
Veelgestelde Vragen

**Comment by Xazin** [comment]
@mudiagauwojeya What is the status here?

**Comment by mudiagauwojeya** [comment]
> @mudiagauwojeya What is the status here?

I was waiting for the translations provided above.

**Comment by Xazin** [comment]
Let me know, I'm ready to approve :D

**Comment by Xazin** [comment]
> Please, hold on a minute. I found a small bug. Fixing it

Let me know if you need help, if it's not important, just leave it :)

**Comment by mudiagauwojeya** [comment]
It is refactor a helper function to account for localization text and realigning a text.

**Comment by mudiagauwojeya** [comment]
This is the final thing that needs fixing, aligning the text with the title. But I am having electrical problems in my home currently and will not be able to fix it tonight till tomorrow. Please, help me fix it @Xazin. Other than that, it is ready for review and merging. Thanks

Screenshot from 2022-12-20 21-29-21

**Review by Xazin — APPROVED** [review]

**Pull request merged**
