### PR TITLE
Feature/donate page

### PR DESCRIPTION
**Pull request by mudiagauwojeya**
# Completed Donate Page UI

This PR implements the donate page UI. Originally, when I read the codebase, I saw that themes were used for the styling but I could not use the available themes in all cases to achieve the design on the Figma board properly. So, I opted for arbitrary values. Therefore, you will find a lot of `w-[300px]` or `max-w-[300px]` because in the tailwind.config there is no config for 300px, the least was 350 for max-width and width does not even have something close. The same is true for other styles.
I tried to be as pixel-perfect to the Figma design as possible and probably violated the DRY standard. I would like some feedback and I am available to work on any adjustments requested upon review. Thanks

### CODE REVIEW

**Comment by Xazin** [comment]
Some comments here:
- When pressing on "one-time donation" the state doesn't change
- I cannot select any other donation amount
- Is `Other...` supposed to be a free-text field, when last selected it should be the chosen option

When pressing on a FAQ, can we make it expand? Despite not clicking on the icon itself.

**Comment by mudiagauwojeya** [comment]
> Some comments here:
> 
>     * When pressing on "one-time donation" the state doesn't change
> 
>     * I cannot select any other donation amount
> 
>     * Is `Other...` supposed to be a free-text field? When last selected it should be the chosen option at least
> 
> 
> When pressing on a FAQ, can we make it expand? Despite not clicking on the icon itself.

That was quick 😄 
- Please, did you pull down the new changes before clicking the one-time donation button? It is working for me and the state is changing as expected because it is a change I added today.
- You're right, I did not implement selecting other donate amount, because I thought that is something that will be done when building the stripe integration. But I can work on it if you're requesting it.
- I do not know what is required for the `Other...` I just made what I saw on the Figma board and didn't think that far about it.

**Comment by Xazin** [comment]
> > Some comments here:
> > ```
> > * When pressing on "one-time donation" the state doesn't change
> > 
> > * I cannot select any other donation amount
> > 
> > * Is `Other...` supposed to be a free-text field? When last selected it should be the chosen option at least
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When pressing on a FAQ, can we make it expand? Despite not clicking on the icon itself.
> 
> That was quick 😄
> 
> * Please, did you pull down the new changes before clicking the one-time donation button? It is working for me and the state is changing as expected because it is a change I added today.
> * You're right, I did not implement selecting other donate amount, because I thought that is something that will be done when building the stripe integration. But I can work on it if you're requesting it.
> * I do not know what is required for the `Other...` I just made what I saw on the Figma board and didn't think that far about it.
> * And yes, I will add a click event to expand the FAQ when the element is clicked besides the button. Thanks

The state of the toggle doesn't change, the donation box itself yes, but not the selected. See:

Screenshot 2022-11-07 at 18 11 22
`One-time donation` is supposed to be black (active state), and `Recurring donation` should be inactive state

**Comment by mudiagauwojeya** [comment]
Hello @Xazin, I have made most of the changes but will need some clarifications about the implementation of the `Other...` field for me to complete my task. In the latest changes I pushed, there is a bug, all the donation amount are active by default, I will fix that tomorrow. But I will like to get any other feedback you have after checking my changes out. Also, please clarify for me so that I can be done with this task by tomorrow. To be sure, I mean clarify for me the way to implement the `Other...` element. What should it be? An input element that lets user enter any other donation amount not specified? Thanks

**Comment by Xazin** [comment]
I'm not able to clarify that for you, instead, @tomsiebring should be able to, or @laschnik .

I will say though, you should squash all of your commits into one commit, 100 commits for 1 feature is not very readable.

**Comment by mudiagauwojeya** [comment]
> I'm not able to clarify that for you, instead, @tomsiebring should be able to, or @laschnik .
> 
> I will say though, you should squash all of your commits into one commit, 100 commits for 1 feature is not very readable.

All 100 commits are not mine, I rebased my branch on the main branch before pushing to remote to incorporate the latest changes in the main and to avoid possible conflicts.

**Comment by mudiagauwojeya** [comment]
@Xazin Hi Mathias, I have finished all the requested changes but there are two things I will like to add before merging upon your approval (and yeah, I still remember I will have to squash the commits). 
- When a user enters a donation amount and submits the form, I think it will be good UX to clear the input field, what do you think? If you agree, can you figure out a way to implement that? 
- Also, I think it will be nicer to add some transition effect to the folding and collapsing of the FAQ components. However, I am also stuck there. I know that the CSS `display` property cannot be transition so I tried to use transform to hide and display the FAQ answer but it is messing up the design. Do you have any suggestions? 
Thanks

**Comment by Xazin** [comment]
You need to rebase and resolve conflicts. 

There have been a few changes to content and pages.

**Comment by mudiagauwojeya** [comment]
I'm all done @Xazin waiting for your approval, after which I will squash and merge this branch.

**Comment by Xazin** [comment]
You should squash first, because after squashing you will need my approval again.

**Pull request merged**
